In [33]:
import requests
import json
from pprint import pp

In [34]:
url = 'https://api.tech.ec.europa.eu/search-api/prod/rest/facet'

params = dict(
    text='***',
    apiKey='SEDIA',
)
resp = requests.post(url=url, params=params)
facets = resp.json()
pp(resp.status_code)

200


In [35]:
pp({d:('list len '+str(len(v)) if isinstance(v,list) else v) for d, v in facets.items()})
pp('Each list entry of "facets" is a dict with "name" and list of "values"')
pp({f['name']: len(f['values']) for f in facets.get('facets')})

{'apiVersion': '2.120', 'terms': '*', 'facets': 'list len 25'}
'Each list entry of "facets" is a dict with "name" and list of "values"'
{'focusArea': 4,
 'programmeDivision': 685,
 'contractType': 5,
 'status': 4,
 'type': 6,
 'crossCuttingPriorities': 42,
 'mainCpv': 2485,
 'placesOfDeliveryOrPerformance': 424,
 'callIdentifier': 15469,
 'frameworkProgramme': 63,
 'programmeDivisionProspect': 31,
 'geographicalZones': 217,
 'procedureType': 19,
 'programmePeriod': 2,
 'mission': 13,
 'destination': 101,
 'typeOfMGAs': 71,
 'missionGroup': 8,
 'destinationGroup': 55,
 'cftSubmissionMethodCode': 5,
 'cftProcurementType': 3,
 'cftPartyLegalEntityId': 95,
 'cftEstimatedOverallContractAmount': 295,
 'cftEstimatedOverallContractCurrency': 16,
 'keywords': 34785}


In [81]:
facetname = 'destination'
{v['rawValue']: v['value'] for v in [f for f in facets['facets'] if f.get('name') == facetname][0]['values']}

{'44799063': 'Sustainable, secure and competitive energy supply (2023/24)',
 '43650711': 'Increased autonomy in key strategic value chains for resilient industry',
 '43650732': 'Sustainable, secure and competitive energy supply',
 '43650762': 'Innovative governance, environmental observations and digital solutions in support of the Green Deal',
 '43650765': 'CONNECT - Interconnected Innovation Ecosystems',
 '43650747': 'Fair, healthy and environmentally-friendly food systems from primary production to consumption',
 '44799054': 'A human-centred and ethical development of digital and industrial technologies (2023/24)',
 '44799078': 'Fair, healthy and environment-friendly food systems from primary production to consumption (2023/24)',
 '43650717': 'Digital and emerging technologies for competitiveness and fit for the Green Deal',
 '44799069': 'Clean and competitive solutions for all transport modes (2023/24)',
 '44799093': 'Innovative governance, environmental observations and digital so

In [56]:
frameworkProgrammes = {v['rawValue']: v['value'] for v in [f for f in facets['facets'] if f.get('name') == "frameworkProgramme"][0]['values']}
pp(frameworkProgrammes)

{'31045243': 'Horizon 2020 Framework Programme (H2020 - 2014-2020)',
 '43108390': 'Horizon Europe (HORIZON)',
 '111111': 'EU External Action (RELEX)',
 '43353764': 'Erasmus+ (ERASMUS+)',
 '44181033': 'European Defence Fund (EDF)',
 '43251567': 'Connecting Europe Facility (CEF)',
 '43251814': 'Creative Europe Programme (CREA)',
 '43152860': 'Digital Europe Programme (DIGITAL)',
 '31109727': 'European Defence Industrial Development Programme (EDIDP - '
             '2014-2020)',
 '43252405': 'Programme for the Environment and Climate Action (LIFE)',
 '31076817': 'Rights, Equality and Citizenship Programme (REC - 2014-2020)',
 '43252476': 'Single Market Programme (SMP)',
 '43251589': 'Citizens, Equality, Rights and Values Programme (CERV)',
 '31070247': 'Justice Programme (JUST - 2014-2020)',
 '42810547': 'Europe Direct (ED - 2014-2020)',
 '31059643': 'Programme for the Competitiveness of Enterprises and small and '
             'medium-sized enterprises (COSME - 2014-2020)',
 '43298664':

In [72]:
callIdentifiers = [f['values'] for f in facets.get('facets') if f['name']=="callIdentifier"][0]
pp(len([(v['rawValue'], v['value']) for v in callIdentifiers if v['rawValue']!=v['value']]))
callIdentifiers = [v['value'] for v in callIdentifiers]
pp(callIdentifiers[:6])

0
['H2020-CS2-CFP08-2018-01',
 'H2020-LC-SC3-2018-2019-2020',
 'H2020-CS2-CFP06-2017-01',
 'H2020-CS2-CFP07-2017-02',
 'H2020-S2RJU-2020',
 'H2020-SC1-BHC-2018-2020']


In [10]:
"We can search for Calls in general"

url = 'https://api.tech.ec.europa.eu/search-api/prod/rest/search'

params = dict(
    text='***',
    apiKey='SEDIA',
    pageSize='100',
)
query={
  "bool": {
    "must": [
      {
        "terms": {
          "type": [
            "1",
            "2",
            "8"
          ]
        }
      },
      {
        "terms": {
          "status": [
            "31094501",
            "31094502",
            "31094503"
          ]
        }
      },
      {
        "term": {
          "programmePeriod": "2021 - 2027"
        }
      },
      {
        "terms": {
          "frameworkProgramme": [
            "43108390"
          ]
        }
      },
      {
        "terms": {
          "crossCuttingPriorities": [
            "PART-COPROGR"
          ]
        }
      },
      {
        "terms": {
          "destination": [
            "43650651"
          ]
        }
      },
      # {
      #   "term": {
      #     "callIdentifier": "HORIZON-INFRA-2021-EOSC-01"
      #   }
      # }
    ]
  }
}

languages = ["en"]
sort = {"field": "sortStatus", "order": "ASC"}

resp = requests.post(url=url, params=params, files={
    'query': ('blob', json.dumps(query), 'application/json'),
    'languages': ("blob", json.dumps(languages), "application/json"),
    'sort': ("blob", json.dumps(sort), "application/json")
 }
)
data = resp.json()
pp(data)

{'apiVersion': '2.120',
 'terms': '***',
 'responseTime': 58,
 'totalResults': 10,
 'pageNumber': 1,
 'pageSize': 100,
 'sort': '[sortStatus:ASC]',
 'groupByField': 'sortStatus',
 'queryLanguage': {'language': 'en', 'probability': 0.0},
 'spellingSuggestion': None,
 'bestBets': [],
 'results': [{'apiVersion': '2.120',
              'reference': '43969539HORIZONCoordinationandSupportActions1624320000000',
              'url': 'https://ec.europa.eu/info/funding-tenders/opportunities/data/topicDetails/HORIZON-INFRA-2021-EOSC-01-01.json',
              'title': None,
              'contentType': 'text/plain',
              'language': 'en',
              'databaseLabel': 'SEDIA',
              'database': 'SEDIA',
              'summary': 'Supporting an EOSC-ready digitally skilled workforce',
              'weight': 0.0,
              'groupById': '3',
              'content': 'Supporting an EOSC-ready digitally skilled workforce',
              'accessRestriction': False,
              '

In [11]:
"We can search for specific Calls"

url = 'https://api.tech.ec.europa.eu/search-api/prod/rest/search'

params = dict(
    text='"HORIZON-EIC-2024-PATHFINDERCHALLENGES-01"',
    apiKey='SEDIA',
    pageSize='100',
)

query = {
  "bool": {
    "must": [
            {"terms": {"type": ["1", "2"]}},
            {"terms": {"status": ["31094501", "31094502", "31094503"]}},
            {"term": {"programmePeriod": "2021 - 2027"}},
            {"terms": {"frameworkProgramme": ["43108390"]}},
        ]
  }
}

languages = ["en"]
sort = {"field": "sortStatus", "order": "ASC"}

resp = requests.post(url=url, params=params, files={
    'query': ('blob', json.dumps(query), 'application/json'),
    'languages': ("blob", json.dumps(languages), "application/json"),
    'sort': ("blob", json.dumps(sort), "application/json")
 })

data = resp.json()
pp(data)

{'apiVersion': '2.120',
 'terms': '"HORIZON-EIC-2024-PATHFINDERCHALLENGES-01"',
 'responseTime': 51,
 'totalResults': 5,
 'pageNumber': 1,
 'pageSize': 100,
 'sort': '[sortStatus:ASC]',
 'groupByField': 'sortStatus',
 'queryLanguage': {'language': 'en', 'probability': 0.0},
 'spellingSuggestion': 'horizon eic <b>2023</b> pathfinderchallenges 01',
 'bestBets': [],
 'results': [{'apiVersion': '2.120',
              'reference': '46553288HORIZONEICGrants1718841600000',
              'url': 'https://ec.europa.eu/info/funding-tenders/opportunities/data/topicDetails/HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-01.json',
              'title': None,
              'contentType': 'text/plain',
              'language': 'en',
              'databaseLabel': 'SEDIA',
              'database': 'SEDIA',
              'summary': 'Solar-to-X devices for the decentralized prosumption '
                         'of renewable fuels, chemicals and materials as '
                         'climate change mitiga

In [12]:
"We can search for specific Topics, apparently"

url = 'https://api.tech.ec.europa.eu/search-api/prod/rest/search'

params = dict(
    text='"HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-01"',
    apiKey='SEDIA',
    pageSize='100',
)

resp = requests.post(url=url, params=params)
data = resp.json()
pp(data)

{'apiVersion': '2.120',
 'terms': '"HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-01"',
 'responseTime': 57,
 'totalResults': 1,
 'pageNumber': 1,
 'pageSize': 100,
 'sort': 'relevance',
 'groupByField': 'sortStatus',
 'queryLanguage': {'language': 'en', 'probability': 0.0},
 'spellingSuggestion': 'horizon <b>ec</b> 2024 pathfinderchallenges 01 01',
 'bestBets': [],
 'results': [{'apiVersion': '2.120',
              'reference': '46553288HORIZONEICGrants1718841600000',
              'url': 'https://ec.europa.eu/info/funding-tenders/opportunities/data/topicDetails/HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-01.json',
              'title': None,
              'contentType': 'text/plain',
              'language': 'en',
              'databaseLabel': 'SEDIA',
              'database': 'SEDIA',
              'summary': 'Solar-to-X devices for the decentralized prosumption '
                         'of renewable fuels, chemicals and materials as '
                         'climate change mitigati

In [13]:
"Older topics return extra results - some filter is needed. More on type [11] later."

url = 'https://api.tech.ec.europa.eu/search-api/prod/rest/search'

params = dict(
    text='"HORIZON-EIC-2022-PATHFINDERCHALLENGES-01-01"',
    apiKey='SEDIA',
    pageSize='100',
)

resp = requests.post(url=url, params=params)
data = resp.json()
pp(data)

{'apiVersion': '2.120',
 'terms': '"HORIZON-EIC-2022-PATHFINDERCHALLENGES-01-01"',
 'responseTime': 73,
 'totalResults': 8,
 'pageNumber': 1,
 'pageSize': 100,
 'sort': 'relevance',
 'groupByField': 'sortStatus',
 'queryLanguage': {'language': 'en', 'probability': 0.0},
 'spellingSuggestion': 'horizon <b>ec</b> 2022 pathfinderchallenges 01 01',
 'bestBets': [],
 'results': [{'apiVersion': '2.120',
              'reference': '44661382HORIZONEICGrants1655337600000',
              'url': 'https://ec.europa.eu/info/funding-tenders/opportunities/data/topicDetails/HORIZON-EIC-2022-PATHFINDERCHALLENGES-01-01.json',
              'title': None,
              'contentType': 'text/plain',
              'language': 'en',
              'databaseLabel': 'SEDIA',
              'database': 'SEDIA',
              'summary': 'EIC Pathfinder Challenge: Carbon dioxide and '
                         'Nitrogen management and valorisation',
              'weight': 10.098313,
              'groupById': '3',


Note: url / esST_URL require lowercasing of identifier (but not topicDetails)

In [14]:
"We can search for Calls in general - wildcard text but callIdentifier, which allows us to respect the rest of the query parameters."

url = 'https://api.tech.ec.europa.eu/search-api/prod/rest/search'

params = dict(
    text='"HORIZON-EIC-2024-PATHFINDERCHALLENGES-01"',
    apiKey='SEDIA',
    pageSize='100',
)
query={
  "bool": {
    "must": [
      {"terms": {"type": ["1", "2", "8"]}},
      {"terms": {"status": ["31094501", "31094502", "31094503"]}},
      {"term": {"programmePeriod": "2021 - 2027"}},
      {"terms": {"frameworkProgramme": ["43108390"]}},
      # {"term": {"callIdentifier": "HORIZON-EIC-2024-PATHFINDERCHALLENGES-01" }}
    ]
  }
}

languages = ["en"]
sort = {"field": "sortStatus", "order": "ASC"}

resp = requests.post(url=url, params=params, files={
    'query': ('blob', json.dumps(query), 'application/json'),
    'languages': ("blob", json.dumps(languages), "application/json"),
    'sort': ("blob", json.dumps(sort), "application/json")
 }
)
data = resp.json()
pp(data)

{'apiVersion': '2.120',
 'terms': '"HORIZON-EIC-2024-PATHFINDERCHALLENGES-01"',
 'responseTime': 60,
 'totalResults': 5,
 'pageNumber': 1,
 'pageSize': 100,
 'sort': '[sortStatus:ASC]',
 'groupByField': 'sortStatus',
 'queryLanguage': {'language': 'en', 'probability': 0.0},
 'spellingSuggestion': 'horizon eic <b>2023</b> pathfinderchallenges 01',
 'bestBets': [],
 'results': [{'apiVersion': '2.120',
              'reference': '46553288HORIZONEICGrants1718841600000',
              'url': 'https://ec.europa.eu/info/funding-tenders/opportunities/data/topicDetails/HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-01.json',
              'title': None,
              'contentType': 'text/plain',
              'language': 'en',
              'databaseLabel': 'SEDIA',
              'database': 'SEDIA',
              'summary': 'Solar-to-X devices for the decentralized prosumption '
                         'of renewable fuels, chemicals and materials as '
                         'climate change mitiga

In [15]:
"Can we do the same for topics? Yes!"

url = 'https://api.tech.ec.europa.eu/search-api/prod/rest/search'

params = dict(
    text='***',
    apiKey='SEDIA',
    pageSize='100',
)
query={
  "bool": {
    "must": [
      {"terms": {"type": ["1", "2", "8"]}},
      {"terms": {"status": ["31094501", "31094502", "31094503"]}},
      {"term": {"programmePeriod": "2021 - 2027"}},
      {"terms": {"frameworkProgramme": ["43108390"]}},
      {"term": {"identifier": "HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-01" }}
    ]
  }
}

languages = ["en"]
sort = {"field": "sortStatus", "order": "ASC"}

resp = requests.post(url=url, params=params, files={
    'query': ('blob', json.dumps(query), 'application/json'),
    'languages': ("blob", json.dumps(languages), "application/json"),
    'sort': ("blob", json.dumps(sort), "application/json")
 }
)
data = resp.json()
pp(data)

{'apiVersion': '2.120',
 'terms': '***',
 'responseTime': 58,
 'totalResults': 1,
 'pageNumber': 1,
 'pageSize': 100,
 'sort': '[sortStatus:ASC]',
 'groupByField': 'sortStatus',
 'queryLanguage': {'language': 'en', 'probability': 0.0},
 'spellingSuggestion': None,
 'bestBets': [],
 'results': [{'apiVersion': '2.120',
              'reference': '46553288HORIZONEICGrants1718841600000',
              'url': 'https://ec.europa.eu/info/funding-tenders/opportunities/data/topicDetails/HORIZON-EIC-2024-PATHFINDERCHALLENGES-01-01.json',
              'title': None,
              'contentType': 'text/plain',
              'language': 'en',
              'databaseLabel': 'SEDIA',
              'database': 'SEDIA',
              'summary': 'Solar-to-X devices for the decentralized prosumption '
                         'of renewable fuels, chemicals and materials as '
                         'climate change mitigation pathway',
              'weight': 0.0,
              'groupById': '1',
        

In [16]:
"It appears type 11 is projects - accessible in json format via https://ec.europa.eu/info/funding-tenders/opportunities/api/orgProfile/publicProjectDetails?projectId=101095219 - but vastly incomplete. Access via JSON is clearly better."

url = 'https://api.tech.ec.europa.eu/search-api/prod/rest/search'

params = dict(
    text='***',
    apiKey='SEDIA',
    pageSize='100',
)
query={
  "bool": {
    "must": [
      {"terms": {"type": ["11"]}},
      # {"terms": {"status": ["31094501", "31094502", "31094503"]}},
      # {"term": {"programmePeriod": "2021 - 2027"}},
      # {"terms": {"frameworkProgramme": ["43108390"]}},
      # {"term": {"identifier": "HORIZON-EIC-2022-PATHFINDERCHALLENGES-01-01" }},
      # {"term": {"callIdentifier": "HORIZON-EIC-2022-PATHFINDERCHALLENGES-01" }},
    ]
  }
}

languages = ["en"]
sort = {"field": "sortStatus", "order": "ASC"}

resp = requests.post(url=url, params=params, files={
    'query': ('blob', json.dumps(query), 'application/json'),
    'languages': ("blob", json.dumps(languages), "application/json"),
    'sort': ("blob", json.dumps(sort), "application/json")
 }
)

data = resp.json()
pp(data)

{'apiVersion': '2.120',
 'terms': '***',
 'responseTime': 109,
 'totalResults': 366,
 'pageNumber': 1,
 'pageSize': 100,
 'sort': '[sortStatus:ASC]',
 'groupByField': 'sortStatus',
 'queryLanguage': {'language': 'en', 'probability': 0.0},
 'spellingSuggestion': None,
 'bestBets': [],
 'results': [{'apiVersion': '2.120',
              'reference': 'HOP_ON_PROJECT101095219',
              'url': 'https://ec.europa.eu/info/funding-tenders/opportunities/horizon/hop-on/101095219',
              'title': None,
              'contentType': 'text/plain',
              'language': 'en',
              'databaseLabel': 'SEDIA',
              'database': 'SEDIA',
              'summary': 'Wellbeing, inclusion, sustainability and the economy',
              'weight': 0.0,
              'groupById': None,
              'content': 'Wellbeing, inclusion, sustainability and the economy',
              'accessRestriction': False,
              'pages': None,
              'checksum': '883B18D11F153C6626

Now, experiment with how to best segment the data so we can actually managably process the db.

In [17]:
url = 'https://api.tech.ec.europa.eu/search-api/prod/rest/search'

params = dict(
    text='***',
    apiKey='SEDIA',
    pageSize='100',
)
query={
  "bool": {
    "must": [
      {"terms": {"type": ["11"]}},
      # {"terms": {"status": ["31094501", "31094502", "31094503"]}},
      # {"term": {"programmePeriod": "2021 - 2027"}},
      # {"terms": {"frameworkProgramme": ["43108390"]}},
      # {"term": {"identifier": "HORIZON-EIC-2022-PATHFINDERCHALLENGES-01-01" }},
      # {"term": {"callIdentifier": "HORIZON-EIC-2022-PATHFINDERCHALLENGES-01" }},
    ]
  }
}

languages = ["en"]
sort = {"field": "sortStatus", "order": "ASC"}

resp = requests.post(url=url, params=params, files={
    'query': ('blob', json.dumps(query), 'application/json'),
    'languages': ("blob", json.dumps(languages), "application/json"),
    'sort': ("blob", json.dumps(sort), "application/json")
 }
)

data = resp.json()
pp(data)

{'apiVersion': '2.120',
 'terms': '***',
 'responseTime': 105,
 'totalResults': 366,
 'pageNumber': 1,
 'pageSize': 100,
 'sort': '[sortStatus:ASC]',
 'groupByField': 'sortStatus',
 'queryLanguage': {'language': 'en', 'probability': 0.0},
 'spellingSuggestion': None,
 'bestBets': [],
 'results': [{'apiVersion': '2.120',
              'reference': 'HOP_ON_PROJECT101095219',
              'url': 'https://ec.europa.eu/info/funding-tenders/opportunities/horizon/hop-on/101095219',
              'title': None,
              'contentType': 'text/plain',
              'language': 'en',
              'databaseLabel': 'SEDIA',
              'database': 'SEDIA',
              'summary': 'Wellbeing, inclusion, sustainability and the economy',
              'weight': 0.0,
              'groupById': None,
              'content': 'Wellbeing, inclusion, sustainability and the economy',
              'accessRestriction': False,
              'pages': None,
              'checksum': '883B18D11F153C6626

In [32]:

url = 'https://api.tech.ec.europa.eu/search-api/prod/rest/search'

params = dict(
    text='***',
    apiKey='SEDIA',
    pageSize='100',
)

query={
  "bool": {
    "must": [
      {"terms": {"type": ["0", "1", "2", "8"]}},
      # {"terms": {"status": ["31094501", "31094502", "31094503"]}},
      # {"term": {"programmePeriod": "2021 - 2027"}},
      # {"terms": {"frameworkProgramme": ["43152860"]}}, #DIGITAL EUROPE PROGRAMME
      {"terms": {"frameworkProgramme": ["43108390"]}}, #HORIZON EUROPE PROGRAMME
      # {"term": {"identifier": "HORIZON-EIC-2022-PATHFINDERCHALLENGES-01-01" }},
      # {"term": {"callIdentifier": "HORIZON-EIC-2022-PATHFINDERCHALLENGES-01" }},
    ]
  }
}

languages = ["en"]
sort = {"field": "sortStatus", "order": "ASC"}

resp = requests.post(url=url, params=params, files={
    'query': ('blob', json.dumps(query), 'application/json'),
    'languages': ("blob", json.dumps(languages), "application/json"),
    'sort': ("blob", json.dumps(sort), "application/json")
 }
)
data = resp.json()
pp(data)

{'apiVersion': '2.120',
 'terms': '***',
 'responseTime': 156,
 'totalResults': 2540,
 'pageNumber': 1,
 'pageSize': 100,
 'sort': '[sortStatus:ASC]',
 'groupByField': 'sortStatus',
 'queryLanguage': {'language': 'en', 'probability': 0.0},
 'spellingSuggestion': None,
 'bestBets': [],
 'results': [{'apiVersion': '2.120',
              'reference': '3701COMPETITIVE_CALLen',
              'url': 'https://ec.europa.eu/info/funding-tenders/opportunities/data/topicDetails/3701COMPETITIVE_CALLen',
              'title': None,
              'contentType': 'text/plain',
              'language': 'en',
              'databaseLabel': 'SEDIA',
              'database': 'SEDIA',
              'summary': 'STAGE SUSTAINABILITY TRANSITION PROGRAMME',
              'weight': 0.0,
              'groupById': '1',
              'content': 'STAGE SUSTAINABILITY TRANSITION PROGRAMME',
              'accessRestriction': False,
              'pages': None,
              'checksum': '8B8E1E7DF5B260E0740EA4BEC

Let's quickly fetch data from the json on the web

In [86]:
url = 'https://ec.europa.eu/info/funding-tenders/opportunities/data/topicDetails/horizon-eic-2022-pathfinderchallenges-01-01.json'
resp = requests.get(url)
pp(resp.status_code)
data = resp.json()
pp(data) 

200
{'TopicDetails': {'type': 0,
                  'ccm2Id': 44661382,
                  'cftId': 0,
                  'identifier': 'HORIZON-EIC-2022-PATHFINDERCHALLENGES-01-01',
                  'title': 'EIC Pathfinder Challenge: Carbon dioxide and '
                           'Nitrogen management and valorisation',
                  'publicationDateLong': 1649030400000,
                  'callIdentifier': 'HORIZON-EIC-2022-PATHFINDERCHALLENGES-01',
                  'callTitle': 'EIC Pathfinder Challenges 2022',
                  'callccm2Id': 44661416,
                  'allowPartnerSearch': True,
                  'frameworkProgramme': {'id': 43108390,
                                         'abbreviation': 'HORIZON',
                                         'description': 'Horizon Europe '
                                                        'Framework Programme '
                                                        '(HORIZON)'},
                  'programmeDivision': [{

See callID ccm2ID 44661382, we can use this to retrieve project list:

In [87]:
url = 'https://ec.europa.eu/info/funding-tenders/opportunities/api/topicProjectsList.json?topicId=44661382'
resp = requests.get(url)
pp(resp.status_code)
data = resp.json()
pp(data) 

200
[{'id': None,
  'programId': '43108390',
  'number': None,
  'acronym': 'CONFETI',
  'call': None,
  'program': 'HORIZON',
  'phase': 'Grant Management',
  'businessIdentifier': '101115182',
  'dashBoardMessagesCount': None,
  'dg': None,
  'duration': None,
  'startDate': None,
  'title': 'Green valorization of CO2 and Nitrogen compounds for making '
           'fertilizers',
  'dashboardMessage': [],
  'actions': []},
 {'id': None,
  'programId': '43108390',
  'number': None,
  'acronym': 'DAM4CO2',
  'call': None,
  'program': 'HORIZON',
  'phase': 'Grant Management',
  'businessIdentifier': '101115488',
  'dashBoardMessagesCount': None,
  'dg': None,
  'duration': None,
  'startDate': None,
  'title': 'Double-Active Membranes for a sustainable CO2 cycle',
  'dashboardMessage': [],
  'actions': []},
 {'id': None,
  'programId': '43108390',
  'number': None,
  'acronym': 'ECOMO',
  'call': None,
  'program': 'HORIZON',
  'phase': 'Grant Management',
  'businessIdentifier': '10111

And we can retrieve the project details using the projectID / businessIdentifier: 101115182

In [88]:
url = 'https://ec.europa.eu/info/funding-tenders/opportunities/api/orgProfile/publicProjectDetails?projectId=101115182'
resp = requests.get(url)
pp(resp.status_code)
data = resp.json()
pp(data) 

200
{'acronym': 'CONFETI',
 'id': '101115182',
 'program': 'HORIZON',
 'programId': '43108390',
 'number': '101115182',
 'rdg': 'EISMEA',
 'abstractText': 'CONFETI project proposes the development of a lab-scale '
                 'validated innovative technology that is able to utilise and '
                 'electrochemically convert CO2 and N2 directly from air or '
                 'flue gases without the use of critical raw materials and '
                 'using renewable energy sources. By the production of urea '
                 'from N (N2 and/or NO3-) and CO2, the project aims to ensure '
                 'a circular and renewable carbon and nitrogen economy by '
                 'recycling and converting the NO3- not consume by the plant '
                 'into ammonia or urea using photocatalytic technologies based '
                 'on sunlight. The technology proposed in the current project '
                 'to synthetize and deliver urea fertilizer to plants will '
